apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
data:
  MYSQL_USER: dXNlcjE=
  MYSQL_PASSWORD: cHcxMjM0
  MYSQL_ROOT_PASSWORD: cm9vdHB3OTg3Ng==
  MYSQL_DATABASE: bXlkYg==