apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret2
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret2
              key: password