# kubetemp/lb.yml
apiVersion: v1
kind: Service
metadata:
    name: nodesjs-sfs-svc
spec:
    sessionAffinity: None
    ports:
    - port: 80
      targetPort: 8080
    selector:
        app: nodejs-sfs